# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0002_auto_20171126_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='date',
            field=models.CharField(default=25, max_length=20),
            preserve_default=False,
        ),
    ]
