# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0003_country_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='dicts',
            field=models.TextField(max_length=500000),
        ),
    ]
